### ISSUE TITLE
Question regarding Pooling

### ISSUE THREAD

**Issue by PatrykChrabaszcz** [xgastaldi/shake-shake#3]
I have a small question (I do not know Torch).

In this code when you make skip connection when decreasing resolution:

     -- Skip path #1
     s1 = nn.Sequential()
     s1:add(nn.SpatialAveragePooling(1, 1, stride, stride))
     s1:add(Convolution(nInputPlane, nOutputPlane/2, 1,1, 1,1, 0,0))

     -- Skip path #2
     s2 = nn.Sequential()
     -- Shift the tensor by one pixel right and one pixel down (to make the 2nd path "see" different pixels)
     s2:add(nn.SpatialZeroPadding(1, -1, 1, -1))
     s2:add(nn.SpatialAveragePooling(1, 1, stride, stride))

Skip path #1 Will take 'top left' pixel in each 2x2 square if I understand it correctly

Skip path #2 Will take 'bottom right' pixel in each 2x2 square. Here is the point I do not understand.
If this code first appends zeros to top and left parts of 'feature image' then it will have lot of pixels with value '0' after this downsampling. It would be better to append zeros to right and bottom and remove first row and first column. So instead of   s2:add(nn.SpatialZeroPadding(1, -1, 1, -1)) use s2:add(nn.SpatialZeroPadding(-1, 1, -1, 1)).

Tell me if it works right now as I described, I might be wrong because as I said I don't know Torch to well.

**Comment by xgastaldi** [comment]
Yes, you are right, adding zeros to the right and bottom is a good idea. I will give it a try when I have some time and will incorporate the change if I see an improvement.

**Comment by PatrykChrabaszcz** [comment]
Thanks for quick response.
I'm trying to rewrite the code to Tensorflow right now.
Can I ask you how long does one epoch take for Cifar 10 and '26 2x32d' configuration

**Comment by xgastaldi** [comment]
2 TITAN X Pascal 26 2x32d -LR 0.2 -batchSize 128: 60s per epoch
1 TITAN X Pascal 26 2x32d -LR 0.1 -batchSize 64: 90s per epoch
CUDA 8.0 / cuDNN v5.1

**Comment by PatrykChrabaszcz** [comment]
Thank you. 
I'm getting almost the same time (I use the same GPU) with tensorflow (98seconds).

**Comment by xgastaldi** [comment]
My mistake, I tried that on GPUs that were already used for another test:
2 TITAN X Pascal 26 2x32d -LR 0.2 -batchSize 128: 33s per epoch
1 TITAN X Pascal 26 2x32d -LR 0.1 -batchSize 64: 51s per epoch

**Comment by PatrykChrabaszcz** [comment]
I also made a mistake, I tried it with a smaller model. Actually it takes longer now. I need to work on it :)
