### ISSUE TITLE
Could you give me some suggestions about some possible ways to improve test accuracy.

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [xgastaldi/shake-shake#5]
Thank your sharing your code!
 Your result is the best one I have seen. Now i try to improve the test error based on your code. Could you give me some suggestions about some possible ways to improve test accuracy?

You can connect me with my private email:  42805959@qq.com.

Thanks.

**Comment by xgastaldi** [comment]
I think that adding more branches would be a logical path. I tried that but when I controlled for the number of parameters the results I obtained were similar to the ones with 2 branches. Maybe there is a way to make this work but I haven't found it yet.
In general I would look at other ways to perform internal data augmentation. The stochastic affine combination is one way but there are maybe more efficient ways to add noise?
