### ISSUE TITLE
Error rates

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [xgastaldi/shake-shake#6]
In the readme.md, you writted :"Table 1: Error rates (%) on CIFAR-10 (Top 1 of the last epoch)".

However the best error rate may not in the last epoch. For example   when the parameter "32*2*96" was used , the top1 error of last epoch and the count the sixth of the epoch were respectively 2.86 and 2.79.

Can I consider the best top1 error is 2.79?
How I select he best top1 error?

**Comment by xgastaldi** [comment]
Please see the question "Top 1 error or best Top 1 error?" that was asked during the ICLR workshop review https://openreview.net/forum?id=HkO-PCmYl
