### ISSUE TITLE
CIFAR 100 training too slow

### ISSUE THREAD

**Issue by Jongchan** [xgastaldi/shake-shake#9]
Hi, I am trying to get the reproduced result in CIFAR 100.

I am using the script in README
```
CUDA_VISIBLE_DEVICES=0,1 th main.lua -dataset cifar100 -depth 29 -baseWidth 64 -groups 4 -weightDecay 5e-4 -batchSize 32 -netType shakeshake -nGPU 2 -LR 0.025 -nThreads 8 -shareGradInput true -nEpochs 1800 -lrShape cosine -forwardShake true -backwardShake false -shakeImage true
```

I checked that the Top1 error is 99 at epoch 111, and I'm afraid that it will not converge in the future.

I am running with up-to-date Torch source (built from source), copied necessary files from fb.resnet in Ubuntu 14.04 / CUDA 8 / CuDNN v4

Should I wait with patience? or is there any extra tricks to see faster convergence?

**Comment by xgastaldi** [comment]
Hmm, that's not normal. With the same script, I am at ~84% after 1 epoch and ~76% after 2 epochs.
Did you try CIFAR-10? If CIFAR-10 works, can you try to deactivate the regularization (-forwardShake false -backwardShake false -shakeImage false) and see if it converges? Without regularization, I am at ~83% after 1 epoch and ~71% after 2 epochs.

**Comment by Jongchan** [comment]
@xgastaldi Thank you for your quick & kind reply.
I will share the printed log for each case ASAP.

**Comment by xgastaldi** [comment]
Hi Jongchan,
Since I did not receive any news from you, I will close the issue for now. Please re-open it if you still have this problem.
